name: Publish

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: bikutadesu/create-npmrc@v1
        with:
          org_name: djereg
          auth_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - run: npm version ${{ github.ref_name }} --no-git-tag-version --allow-same-version
      - run: npm ci --no-audit
      - run: npm run build
      - run: npm publish

